config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :patients
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ApplicationRecord
    belongs_to :user#, class_name: "user", foreign_key: "user_id"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :patient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  # GET /patients or /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    #@patient = Patient.new
    @patient = current_user.patient.build
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    #@patient = Patient.new(patient_params)
    @patient = current_user.patient.build(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @patient = current_user.patient.find_by(id: params[:id])
    redirect_to patients_path, notice:"Sai fora. Não é seu paciente" if @patient.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :birth_date, :mass, :height, :attendance_date, :place, :clinical_case, :current_medication, :prescribed_medication, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to "Pacientes Online", root_path, class: "navbar-brand" %>
   
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to "Sobre", home_about_path, class: "nav-link active" %>
        </li>

      <% if user_signed_in? %>

        
        <li class="nav-item">
            <%= link_to "Meus pacientes", patients_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
            <%= link_to "Cadastrar novo paciente", new_patient_path, class: "nav-link active" %>
        </li>
      <div style="width:150px">
      </div>
      <div class="me-center">
      <!--<form class="d-flex" style="width: 400px">
        <input class="form-control me-2 " type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>-->
      </ul>
      </div>
      <div style="width:20px">
      </div>

        <ul class="navbar-nav me-right ml-1 mb-2 mb-lg-0 " style="width: 200px">
        <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link active" %>
        </li>
        <li class="nav-item">
            <%= link_to "Editar Perfil", edit_user_registration_path, class: "nav-link active" %>
        </li>

      </ul>
      <% else %>
      </ul>
        <ul class="navbar-nav me-right ml-1 mb-2 mb-lg-0 " style="width: 200px">
        <li class="nav-item">
            <%= link_to "Registre-se", new_user_registration_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link active" %>
        </li>
        </ul>
      <% end %>
        

    </div>
  </div>
</nav>

app/views/home/about.html.erb
pagina sobre

app/views/home/index.html.erb
<h1>Pagina Inicial</h1>
<p>O intuito dessa tecnologia é treinar programação no ruby on rails,
para tal, fiz um programa para mostrar aos médicos seus pacientes</p>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="pt-BR">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>Atendimentos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <br/>
    <%= render 'home/header' %>
    <div class = "container">
    <br/>
    <% if notice %>
      <%= render 'layouts/alert' %>
    <% end %>
      <br/>
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: patient) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


 <br/>
    <div class="form-row align-items-center">
      <div class="form-group col-md-12 divTableCell">
        <% form.label :first_name %>
        <%= form.text_field :first_name, class: "form-control form-inline", placeholder:"Primeiro Nome" %>
      </div>
 <br/>
      <div class="form-group col-md-12 divTableCell">
        <% form.label :last_lame %>
        <%= form.text_field :last_name, class: "form-control form-inline", placeholder:"Sobrenome" %>
      </div>
    </div>
 <br/>
  <div class="date_field" >
    <%= form.label :"Data Aniversário" %>
    <%= form.date_field :birth_date, id: 'date' %>

    <%= form.label :"Data atendimento" %>
    <%= form.date_field :attendance_date, id: 'date' %>

  </div>
 <br/>

  <div class="field form  col-md-12">
    <% form.label :mass %>
    <%= form.text_field :mass, class: "form-control", placeholder:"Massa" %>
  </div>
<br/>
  <div class="field form  col-md-12">
    <% form.label :height %>
    <%= form.text_field :height, class: "form-control", placeholder:"Altura" %>
  </div>

<br/>

  <div class="field form">
    <% form.label :place %>
    <%= form.text_field :place, class: "form-control", placeholder:"Local" %>
  </div>
   <br/>

  <div class="field form">
    <% form.label :clinical_case %>
    <%= form.text_area  :clinical_case, class: "form-control", placeholder:"Caso Clinico", rows:3 %>
  </div>
<br/>
  <div class="field form">
    <% form.label :current_medication %>
    <%= form.text_field :current_medication, class: "form-control", placeholder:"Medicação Atual" %>
  </div>
<br/>
  <div class="field form">
    <% form.label :prescribed_medication %>
    <%= form.text_field :prescribed_medication, class: "form-control", placeholder:"Prescrição Médica" %>
  </div>
<br/>
  <div class="field form">
    <%= form.number_field :user_id, id: :patient_user_id, class: "form-control", value: current_user.id, type: :hidden %>
  </div>
  
  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
  
  <% end %>
 <br/> 

app/views/patients/edit.html.erb
<h1>Editar Paciente</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient , class:"btn btn-secondary" %>
<%= link_to 'Back', patients_path , class:"btn btn-secondary" %>
 <br/> <br/> <br/>

app/views/patients/index.html.erb
<h1>Patients</h1>
<br/>
<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr class="text-center align-middle">
      <th>Nome</th>
      <th>Data de Nascimento</th>
      <th>Data Atendimento</th>
      <th>Local Atendimento</th>
      <th>Caso Clinico</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <% if patient.user == current_user %>
        <tr class="text-center align-middle">
          <td>
            <%= link_to patient.first_name + " " + patient.last_name, patient %>         
            </td>
          <td><%= patient.birth_date %></td>
          <td><%= patient.attendance_date %></td>
          <td><%= patient.place %></td>
          <td><%= patient.clinical_case %></td>
          <td><%= link_to 'Edit', edit_patient_path(patient), class:"btn btn-outline-primary center" %></td>
          <td ><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path, class:"btn btn-secondary" %>

app/views/patients/new.html.erb
<h1>Novo Paciente</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path , class:"btn btn-secondary" %>
 <br/> <br/> <br/>

app/views/patients/show.html.erb
<%
def age(dob)
  now = Time.now.utc.to_date
  now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
end
%>

<div class="jumbotron">
  <h1 class="display-4"><%= @patient.first_name %> <%= @patient.last_name %>, <%= age(@patient.birth_date) %> anos</h1>
  <p class="my-4">
 <hr class="my-4">
    <p>
      <strong>Data de Nascimento:</strong>
      <%= @patient.birth_date %> 
        </p>
      <strong>Massa:</strong>
      <%= @patient.mass %> Kg
         </p>
      <strong>Altura:</strong>
      <%= @patient.height %> M
      
    </p>

    <p>
      <strong>Data de Atendimento:</strong>
      <%= @patient.attendance_date %>
         </p>
      <strong>Local:</strong>
      <%= @patient.place %>
    </p>

    <p>
      <strong>Caso Clinico:</strong>
      <%= @patient.clinical_case %>
    </p>

    <p>
      <strong>Medicação Atual:</strong>
      <%= @patient.current_medication %>
         </p>
      <strong>Medicação Prescrita:</strong>
      <%= @patient.prescribed_medication %>


    </p>
  </p>
  <br/>
  <p class="lead">
    <%= link_to 'Edit', edit_patient_path(@patient), class:"btn btn-secondary" %>
    <%= link_to 'Back', patients_path , class:"btn btn-secondary" %>

  </p>
</div>